[project]
name = "three-jpnb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anywidget[dev]>=0.9.18",
    "jupyterlab>=4.4.10",
    "shapely>=2.1.2",
]
